<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leadership</name>
   <tag></tag>
   <elementGuidId>42f0fdde-9b43-49d1-a0cb-52eb9f5589ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='primary']/article/section/div/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wp-block-button__link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3d8af73-008e-40ed-b3c4-d2636bf7361d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link</value>
      <webElementGuid>ee8e1848-62e3-4dd8-91fd-0980187d3648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wmg.com/leadership/</value>
      <webElementGuid>58c71a03-a013-4713-ac51-cbbfdfee48d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leadership</value>
      <webElementGuid>eb67f5b5-8817-4c6e-86a9-95d46cb1ec7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary&quot;)/article[1]/section[@class=&quot;page-content content-margins content-container centered-margins&quot;]/div[@class=&quot;split-block alignfull&quot;]/div[@class=&quot;split-block__left&quot;]/div[@class=&quot;split-block__left-inner has-sky-blue-background-color&quot;]/div[@class=&quot;split-block__left-inner-adjuster&quot;]/div[@class=&quot;split-block__left__content-outer&quot;]/div[@class=&quot;split-block__left__content&quot;]/div[@class=&quot;wp-container-1 wp-block-buttons&quot;]/div[@class=&quot;wp-block-button is-style-fill&quot;]/a[@class=&quot;wp-block-button__link&quot;]</value>
      <webElementGuid>7085f655-4bdd-4e09-975d-9ad8c2c47a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='primary']/article/section/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>9508d4c4-e056-4934-aebe-09b1623800a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leadership')]</value>
      <webElementGuid>385ad2b6-b208-47c5-a5e6-35fe24671dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='we are'])[1]/following::a[1]</value>
      <webElementGuid>b0f00002-5fa1-487a-bbb2-f70fe25f6c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Relations'])[1]/preceding::a[3]</value>
      <webElementGuid>3ff17a99-3011-44db-9ec7-2ec48e60a38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People &amp; Workplace'])[1]/preceding::a[4]</value>
      <webElementGuid>8414b2e4-ef91-4cec-81b9-71fe1d048303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leadership']/parent::*</value>
      <webElementGuid>c73f95df-d606-4486-bd0d-12bba06c6741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wmg.com/leadership/')]</value>
      <webElementGuid>9a088713-b914-4c14-a793-541e5cf4e652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>1bded769-4b04-4ab4-ba5a-c034b03e688e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wmg.com/leadership/' and (text() = 'Leadership' or . = 'Leadership')]</value>
      <webElementGuid>8b3a9ad6-e51e-4977-8608-8da1fb20a49f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
