<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Music Publishing</name>
   <tag></tag>
   <elementGuidId>47a5b35d-de09-4f14-8038-20310e145c86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2248']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2248 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d31ca4af-4634-4190-a2fc-bef368fdd72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wmg.com/music-publishing</value>
      <webElementGuid>53b5ef76-b204-4f62-8059-b5b1aaa9f2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Music Publishing</value>
      <webElementGuid>38de2656-5f6f-4875-93f1-c4205997fc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2248&quot;)/a[1]</value>
      <webElementGuid>f58067ef-f748-4ee6-bddf-610c49ef7d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2248']/a</value>
      <webElementGuid>84fa257f-6980-4064-9054-06e49e826da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Music Publishing')]</value>
      <webElementGuid>1a5be011-1a60-4d18-85f3-c10deb92ef40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recorded Music'])[1]/following::a[1]</value>
      <webElementGuid>32a9a383-19d1-46ce-a04b-ac33da99eb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle main navigation'])[1]/following::a[2]</value>
      <webElementGuid>1e433ebf-576c-4b69-9f79-d2cd80e73ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands &amp; Media'])[1]/preceding::a[1]</value>
      <webElementGuid>9135bc8d-d50c-4e2c-ab82-7f9bcaf45cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::a[2]</value>
      <webElementGuid>63d14e7d-cb7c-45c9-a078-3acd3a49a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Music Publishing']/parent::*</value>
      <webElementGuid>6f5cf6c4-cd63-40bb-bec1-e7f063967b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wmg.com/music-publishing')]</value>
      <webElementGuid>82945d5e-14b0-4e69-9bab-55d372d4527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>8aeedd59-7e6a-4942-84a6-e4650c7c4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wmg.com/music-publishing' and (text() = 'Music Publishing' or . = 'Music Publishing')]</value>
      <webElementGuid>64224ff5-1810-4f30-89f7-f57ce3efadf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
