<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Social Justice Fund</name>
   <tag></tag>
   <elementGuidId>94e008a4-c8d6-4004-8ab5-80deb1e6515f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4109']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4109 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f2b7123-f23e-44c1-86f3-ff2ddd1fad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wmg.com/fund</value>
      <webElementGuid>da199ec1-b0d9-4fa9-96b4-59fa1dd405ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Social Justice Fund</value>
      <webElementGuid>56a59e51-f98f-40ee-bf4f-0c2882ebdda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4109&quot;)/a[1]</value>
      <webElementGuid>b1f35d01-539c-4dc8-ab4a-372b187487ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4109']/a</value>
      <webElementGuid>bc5303a5-993f-41e9-9f3c-e63c69fd86a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Social Justice Fund')]</value>
      <webElementGuid>7c7b0aaa-89cc-498c-b37a-1b86836e5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::a[1]</value>
      <webElementGuid>34888b3d-1e79-4793-8ea2-337840608e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::a[2]</value>
      <webElementGuid>3ac507e4-d61a-4f2a-a13a-b60386bbae77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investor Relations'])[1]/preceding::a[1]</value>
      <webElementGuid>a462c37b-91f1-457a-b570-8dfe13319c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artist Royalties'])[1]/preceding::a[2]</value>
      <webElementGuid>460b7c94-a0b7-45b1-bcce-94236c455aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Social Justice Fund']/parent::*</value>
      <webElementGuid>efaec324-0948-4931-b050-4f5dbbf9531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wmg.com/fund')]</value>
      <webElementGuid>246690e7-9c90-41ae-bc50-c28aa8a210f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/ul[2]/li[3]/a</value>
      <webElementGuid>c9b6be9c-cf8e-443f-bb09-aa18b3b739f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wmg.com/fund' and (text() = 'Social Justice Fund' or . = 'Social Justice Fund')]</value>
      <webElementGuid>64a804b1-506f-4a8a-a9ec-2ba979337688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
