<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Recorded Music</name>
   <tag></tag>
   <elementGuidId>fe1b64d1-3e34-4ebe-a35c-7d9f8cf5ffb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2249']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2249 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63e4bfd2-db53-4bcd-ad82-98afc313c296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wmg.com/recorded-music</value>
      <webElementGuid>ee414bba-424b-4e0c-bb12-f5101430a572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recorded Music</value>
      <webElementGuid>41feb923-d92b-4293-b9ee-c24b48e1dc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2249&quot;)/a[1]</value>
      <webElementGuid>e67ee8a7-91f6-47f7-ac0a-78eef430c56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2249']/a</value>
      <webElementGuid>9083579d-7051-4255-a379-8a525138e17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Recorded Music')]</value>
      <webElementGuid>798e72e8-5d01-4d15-b0d5-c9c9c64dc2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle main navigation'])[1]/following::a[1]</value>
      <webElementGuid>08932292-957e-4933-9f06-bec8e717e4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warner Music Group'])[1]/following::a[1]</value>
      <webElementGuid>49548f1c-1b6b-43f5-9133-7d5d59e92b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Music Publishing'])[1]/preceding::a[1]</value>
      <webElementGuid>53d4c728-8e20-437b-ae19-6f30febc2245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands &amp; Media'])[1]/preceding::a[2]</value>
      <webElementGuid>05d11a96-83fa-4169-887f-b3da851803a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recorded Music']/parent::*</value>
      <webElementGuid>e9792806-9f7b-4997-81f9-3bec19f833e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wmg.com/recorded-music')]</value>
      <webElementGuid>a1f9b133-4569-4ceb-a251-ad59e5889fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>7d4cc4a4-f92f-4135-8228-3fc4efee46d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wmg.com/recorded-music' and (text() = 'Recorded Music' or . = 'Recorded Music')]</value>
      <webElementGuid>358ec485-0a7d-4672-9f95-e72261c57e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
