<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Recorded Music</name>
   <tag></tag>
   <elementGuidId>c9aed884-254c-4a63-893e-2bae7a143660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2249']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2249</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>028810d1-8603-43f2-9131-e7e298b4dd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-2249</value>
      <webElementGuid>4c7408ec-6761-42c1-ac0d-76d7f8303342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item menu-item-type-post_type menu-item-object-page menu-item-2249</value>
      <webElementGuid>574dae7a-5027-46e5-9c60-84858e04bb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recorded Music</value>
      <webElementGuid>1b74e1b8-e167-4911-ac8d-c690c461ecfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2249&quot;)</value>
      <webElementGuid>ca7a1fb2-0ff2-400d-a270-4222950508c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2249']</value>
      <webElementGuid>c1f670b6-c581-4d3f-a50a-e6d321769d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-navigation']/li</value>
      <webElementGuid>55d24b2b-2b86-4481-a3d1-e07c393c6915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle main navigation'])[1]/following::li[1]</value>
      <webElementGuid>0bd4eef8-b1fe-48cd-ae20-7f4eb6b664b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warner Music Group'])[1]/following::li[1]</value>
      <webElementGuid>3aa2ec13-76d7-4edc-8064-ad77246efce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Music Publishing'])[1]/preceding::li[1]</value>
      <webElementGuid>0ccdafdb-dd82-4eeb-b677-0dc1c6d22a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>6f909858-f695-404b-9759-30cfef9fb8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'menu-item-2249' and (text() = 'Recorded Music' or . = 'Recorded Music')]</value>
      <webElementGuid>2e88eb52-353c-4945-8411-4da6021de84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
